# Generated by Django 3.1.5 on 2021-01-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rated',
            new_name='rated_goals',
        ),
    ]
