# Generated by Django 3.1.5 on 2021-01-22 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_auto_20210119_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')]),
        ),
    ]
